default_platform(:ios)

platform :ios do
  desc "Build the app"
  lane :build do
    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "Friendly.ipa"
    )
  end

  desc "Upload to TestFlight"
  lane :beta do
    build
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Upload to App Store"
  lane :release do
    build
    upload_to_app_store(
      force: true,
      skip_screenshots: true,
      submit_for_review: false
    )
  end

  desc "Upload metadata only (no build)"
  lane :metadata do
    upload_to_app_store(
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true
    )
  end
end
